<a href="https://colab.research.google.com/github/asha15/Secure-and-Private-AI-scholarship-/blob/master/adding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import torch

x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

print(torch.add(x, y))

tensor([[0.3092, 0.4725, 0.1297],
        [0.7157, 0.4803, 0.7635],
        [0.1363, 0.9681, 0.5190],
        [0.5289, 0.4403, 0.9330],
        [0.3080, 0.4826, 0.7979]])
tensor([[0.5489, 0.4808, 0.4101],
        [0.8511, 0.9570, 0.1685],
        [0.5120, 0.0894, 0.0143],
        [0.8327, 0.9845, 0.1411],
        [0.5212, 0.5620, 0.9247]])
tensor([[0.8581, 0.9533, 0.5398],
        [1.5668, 1.4373, 0.9320],
        [0.6482, 1.0574, 0.5333],
        [1.3616, 1.4248, 1.0741],
        [0.8291, 1.0446, 1.7227]])
tensor([[0.8581, 0.9533, 0.5398],
        [1.5668, 1.4373, 0.9320],
        [0.6482, 1.0574, 0.5333],
        [1.3616, 1.4248, 1.0741],
        [0.8291, 1.0446, 1.7227]])
